# Configuration template for the mosquitto user configuration
#
# A full description of the configuration file is at
# /usr/share/doc/mosquitto/examples/mosquitto.conf

listener 0 /run/user/1001/mosquitto/mosquitto.socket 

# We rely on socket permissions here. This needs to be changed if mosquitto is 
# listening on a port.
allow_anonymous true

pid_file /run/user/1001/mosquitto/mosquitto.pid

persistence true
persistence_location /home/beast/.local/state/mosquitto

log_dest file /home/beast/.local/state/log/mosquitto/mosquitto.log

